services:
  - type: web
    name: proof-of-meme
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PRIVATE_KEY
        sync: false
      - key: CONTRACT_ADDRESS
        value: "0xFD665Bdc770a70ADe50D9641A1705f046773FD9e"
      - key: RPC_URL
        value: "https://rpc-bradbury.genlayer.com"
